# site settings
title: Bård Berg
subtitle: musikk
email: 
description: Trommis, produsent, DJ - Oslo
baseurl: "/bardberg" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city:
state: 
zip_code:
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/bardjb
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/bardkrolle
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 
spotify_url: https://open.spotify.com/artist/6cj0DfbcgWVo53BtyTEH6r?si=6AfQJEAkSbKUH-Xd4tOvYw

# build settings
markdown: kramdown

sass:
  style: compressed
