# site settings
title: Bård Berg
subtitle: musikk
email: 
description: Trommis, produsent, DJ - Oslo.
baseurl: # the subpath of your site, e.g. /blog
url: bardberg.ninja
author:
street_address: 
city:
state: 
zip_code:
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
facebook_url: https://www.facebook.com/bardjb
instagram_url: https://instagram.com/bardkrolle
spotify_url: https://open.spotify.com/artist/6cj0DfbcgWVo53BtyTEH6r?si=6AfQJEAkSbKUH-Xd4tOvYw
soundcloud_url: https://soundcloud.com/b-rd-j-nland-berg

# build settings
markdown: kramdown

sass:
  style: compressed
